# Generated by Django 3.2 on 2021-04-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='IDCard',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
    ]
