# Generated by Django 3.2 on 2021-04-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Display', '0003_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=1, verbose_name='工作人员状态'),
        ),
    ]
